[env:esp32-s3-devkitc-1]
platform = espressif32
board = rymcu-esp32-s3-devkitc-1  ;es el mismo que esp32-s3-devkitc-1 pero con PSRAM
board_build.psram = 1  ; Habilita PSRAM
framework = arduino

; Configuración para N16 (16MB Flash)
board_build.arduino.memory_type = qio_opi ; Crucial para modelos con PSRAM OPI 
board_build.f_flash = 80000000L ; Aumenta la velocidad de lectura de flash para mejorar el rendimiento del modelo
board_build.flash_mode = qio 
board_upload.flash_size = 16MB  ; Configuración de tamaño de flash para N16


build_flags =
    -DBOARD_HAS_PSRAM   ; Habilita el uso de PSRAM
    -DCONFIG_SPIRAM ; Habilita el uso de PSRAM en el sistema--------------
    -DCONFIG_SPIRAM_USE_MALLOC   ; Permite usar malloc para PSRAM-----------
    -mfix-esp32-psram-cache-issue  ; Soluciona problemas de caché con PSRAM
    -I lib/tfmicro/src
    -I lib/tfmicro/src/third_party/flatbuffers/include
    -I lib/tfmicro/src/third_party/gemmlowp
    -I lib/tfmicro/src/third_party/fixedpoint
    ;-D TF_LITE_STATIC_MEMORY
    ;-D TF_LITE_DISABLE_X86_NEON

; Monitor serial
monitor_speed = 115200 ; Velocidad del monitor serial